/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdio.h>
#include <android/log.h>
/* Header for class trio_com_jniexceptionhandler_Calculate */

#ifndef _Included_trio_com_jniexceptionhandler_Calculate
#define _Included_trio_com_jniexceptionhandler_Calculate
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     trio_com_jniexceptionhandler_Calculate
 * Method:    jniAdd
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_trio_com_jniexceptionhandler_Calculate_jniDivide
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif

#define LOG_TAG "JNILog"
#define LOGV(...) __android_log_print(ANDROID_LOG_VERBOSE, LOG_TAG, __VA_ARGS__)
#define LOGD(...) __android_log_print(ANDROID_LOG_DEBUG, LOG_TAG, __VA_ARGS__)
#define LOGI(...) __android_log_print(ANDROID_LOG_INFO, LOG_TAG, __VA_ARGS__)
#define LOGW(...) __android_log_print(ANDROID_LOG_WARN, LOG_TAG, __VA_ARGS__)
#define LOGE(...) __android_log_print(ANDROID_LOG_ERROR, LOG_TAG, __VA_ARGS__)

